server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://manishk57107:mgonDAXTEP4tfY5s@cluster0.gllnrkk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

